### ISSUE TITLE
TrpPage.getTranscripts() does not return old versions of a page

### ISSUE THREAD

**Issue by shomauno** [Transkribus/TranskribusCore#12]
There is no obvious button in the Transkribus GUI to compute accuracy between two versions of a page.
![compute accuracy](https://user-images.githubusercontent.com/16329988/27195071-3da31b0a-51d3-11e7-8b51-4e5744c252e8.png)

While attempting to gather two different transcription versions of my page and run the comparison using the Transkribus code directly, I found that the getTranscripts() method did not return more than one transcript per page, even though I had multiple versions.

![multiple versions](https://user-images.githubusercontent.com/16329988/27195257-0c59fdce-51d4-11e7-9f22-f76c7a0cea50.png)

If this is an error in my understanding of the program, please advise.

**Comment by jkloe** [comment]
Regarding the UI: first you have to choose the reference transcript version using the "Choose..." button and the Hypothesis the same way. Then click on the "Compare" button below and the CER / WER will be shown in a new dialog.

Regarding the TrpPage.getTranscripts() method: which code did you use to get the TrpPage object?

**Comment by shomauno** [comment]
Thank you! I was using a small computer screen and the icons did not resize, so the problem was that I did not zoom out and open a full screen view. Perhaps icon resizing could be a desirable future goal to ease usability.

I wrote my own code which opens a TrpServerConn connection, gathers the TrpCollection I want, loops through the TrpDocMetadata documents present in that collection (using the TrpServerConn's getAllDocs(columnID) method), finds the appropriate TrpDoc using the columnID and documentID, and then loops through the TrpPages of that document. When I call getTranscripts() on the page, only the latest version is returned in the List<TrpTranscriptMetadata>, so I can only access one transcript version.

**Comment by jkloe** [comment]
Ok, so if you query for the TrpDoc using collection-id and doc-id you should use the method TrpServerConn.getTrpDoc which has as third parameter "nrOfTranscriptsPerPage". If you set this to -1 you should get all transcripts. Hope that helps.

**Comment by shomauno** [comment]
Thanks a lot! I had set the argument to 1, which explains my problem.
