### ISSUE TITLE
DocExporter: files are overwritten if duplicate filenames occur

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusCore#13]
Exporting a document fails, if there are duplicate original filenames within the document.
Files are then silently overwritten.

Reproduce on "TEST_CITlab_Konzilsprotokolle M4" (Doc ID 18718): When exporting all 28 pages, the result includes only 6 images!

**Comment by jkloe** [comment]
- [ ] ~~add option to prefix an increasing number to the filenames -> should be set to true by default, if unchecked in UI, give the user a warning. This also ensures that the right order of the files is retained.~~
- [x] make sure that those modified filenames are respected in all exports (PAGE, imgs, ALTO, TEI ... )

**Comment by jkloe** [comment]
Problem currently only occurs for training set documents which are constructed from pages of other documents. Can however also occur if the user adds pages to the document after uploading and those pages have the same filename as one of the pages in the existing document.
