### ISSUE TITLE
TranskribusCore does not compile on Java 9

### ISSUE THREAD

**Issue by jkloe** [Transkribus/TranskribusCore#27]
ClassNotFoundExceptions in JaxbUtils::createJAXBContext:
    java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
Must be related with JAXB issues in Java 9...

**Comment by kahlep** [comment]
pom.xml has to be adapted to use Java 9 module system as java.xml.bind (=JAXB API) is not in the base module of Java anymore.
Found guide that may be helpful here: https://blog.codefx.org/java/java-9-migration-guide/

```                     
<plugin>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.1</version>
	<configuration>
		<source>1.8</source>
		<target>1.8</target>
		<compilerArgs>
			<!-- add JaxB Module for Java9 -->
			<arg>--add-modules</arg>
			<arg>java.xml.bind</arg>
		</compilerArgs>
	</configuration>
</plugin>
```

Another problem (happens on my system and is also described in the guide) is this cast of ClassLoader to URLClassLoader: https://github.com/Transkribus/TranskribusSwtGui/blob/master/src/main/java/eu/transkribus/util/Utils.java#L200

A user reported that Transkribus 1.3.5 runs on Java 9 by Oracle but not with OpenJDK 9. This has to be investigated too.

- [ ] fix cast of ClassLoader (see link above)
- [ ] Switch dev systems (and Jenkins) to Java 9 which is then required to build Transkribus apps
- [ ] ensure that builds run on Oracle Java and OpenJDK, for both distributions versions 8 & 9

**Comment by kahlep** [comment]
ClassLoader problem is described further here: https://github.com/Transkribus/TranskribusSwtGui/issues/198

**Comment by jkloe** [comment]
https://stackoverflow.com/questions/52502189/java-11-package-javax-xml-bind-does-not-exist
http://timepassguys.blogspot.com/2011/12/jaxb-exception-javaxxmlbindpropertyexce.html
