### ISSUE TITLE
Off-by-one error in DocExporter.exportDoc() with subset of pages

### ISSUE THREAD

**Issue by jscrane** [Transkribus/TranskribusCore#30]
If I try to export a subset of pages (e.g., {1, 3, 5}) from a document, I actually get pages {2, 4, 6}.

I think this is due to the test in exportDoc() at line 228, "pageIndices.contains(i)".

Shouldn't this be something like "pageIndices.contains(p.getPageNr())"?

**Comment by hackmanschorsch** [comment]
Can't reproduce this at the moment. For me it works. PageIndices run from 0-n and i iterates over 0-n, so this should be fine. So I think you just have to know that the parameter is not the page number but the page index. So it's a matter of documentation - sorry about that!

**Comment by jscrane** [comment]
Right, I thought it was page-numbers. (They seem to be converted into "page indices" by CoreUtils.parseRangeListStr.)
