### ISSUE TITLE
openJDK v 11 ? 

### ISSUE THREAD

**Issue by u-jung** [Transkribus/TranskribusCore#31]
Hello,

there is some trouble with starting Transkribus.sh on Ubuntu Bionic.
```
>> ./Transkribus.sh
Starting Transkribus - first trying to find java, your OS = linux-gnu
Found java executable in PATH
Java bin = java
Java version >= 1.7 required!
```

But `
````
>> java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
```

I've tried to change the java alternatives but without succes:

```
>> sudo update-alternatives --config java
Es gibt 2 Auswahlmöglichkeiten für die Alternative java (welche /usr/bin/java bereitstellen).

  Auswahl      Pfad                                            Priorität Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      automatischer Modus
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1101      manueller Modus
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manueller Modus

```
`
Does Transkribus work with openJDK v 11?

Greetings

U. Jung

**Comment by kahlep** [comment]
Hello,
yes, there is some code that is incompatible with Java version >= 9 and not yet adapted.

Setting Java version 8 with update-alternatives is what I do too and it works. In my case it's an Oracle JDK but OpenJdk should work fine too.

What's the error message after updating alternatives please?

**Comment by kahlep** [comment]
Hello,
there is indeed some code included that is not compatible to Java version >= 9 and was not yet adapted.

Setting Java 8 by update-alternatives is what I do too. In my case it's an Oracle JDK but OpenJDK should work fine too.

What's the error message with OpenJDK 8 in your case?

**Comment by kahlep** [comment]
see Transkribus/TranskribusSwtGui#198
