### ISSUE TITLE
page2alto style not valid

### ISSUE THREAD

**Issue by tboenig** [Transkribus/TranskribusCore#39]
see the line: https://github.com/Transkribus/TranskribusCore/blob/f185e3df59ca3634ff56390d685373fbbcfe1401/src/main/resources/xslt/PageToAlto.xsl#L327

The comments are not close. If you comment a paragraph or lines you must use square brackets:
```xml
<!-- [styles not used for now/>
            <xsl:call-template name="applyStyleId"/>
            <if textline without words then we create a new String with the total textline as CONTENT  ]-->
```

**Comment by hackmanschorsch** [comment]
thanks for the hint - we use 'PageToAltoWordLevel.xsl' since a while and there everything should be fine now
