### ISSUE TITLE
Flag to mark collections as open for crowd-sourcing

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TranskribusCore#4]
Binary flag. Set (initially) in expert tool. Available via REST interface to allow crowd-sourcing apps to determine if a collection is available for use.

**Comment by kahlep** [comment]
The collections on the test server already come with the flag set. 
Check the GET paths for listing crowdsourcing collections, no login needed:
* https://transkribus.eu/TrpServerTesting/rest/crowdsourcing/list
* https://transkribus.eu/TrpServerTesting/rest/crowdsourcing/count
(Count method is needed as the list path allows for paging)

Logged in users are able to (un-)subscribe with a POST to:
* https://transkribus.eu/TrpServerTesting/rest/crowdsourcing/{collection_ID}/subscribe
* https://transkribus.eu/TrpServerTesting/rest/crowdsourcing/{collection_ID}/unsubscribe

On subscribing, a user with role:
* None: gets the role CrowdTranscriber
* Reader: is promoted to CrowdTranscriber
* greater than Reader: no modification is done.

Unsubscribing is only possible as CrowdTranscriber.

Unfortunately there is one glitch: using those methods, a Reader could promote and than remove himself from a collection but storing recent roles is too much I think.
